declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react'

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number
    color?: string
    strokeWidth?: string | number
    absoluteStrokeWidth?: boolean
  }

  export type LucideIcon = ComponentType<LucideProps>

  export const Home: LucideIcon
  export const Search: LucideIcon
  export const Calendar: LucideIcon
  export const CreditCard: LucideIcon
  export const User: LucideIcon
  export const LogOut: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const Users: LucideIcon
  export const Store: LucideIcon
  export const Settings: LucideIcon
  export const Plus: LucideIcon
  export const PlusCircle: LucideIcon
  export const Edit: LucideIcon
  export const Trash2: LucideIcon
  export const Eye: LucideIcon
  export const Check: LucideIcon
  export const X: LucideIcon
  export const Wallet: LucideIcon
  export const Bus: LucideIcon
  export const MapPin: LucideIcon
  export const Star: LucideIcon
  export const TrendingUp: LucideIcon
  export const DollarSign: LucideIcon
  export const Bell: LucideIcon
  export const Menu: LucideIcon
  export const Hotel: LucideIcon
  export const Compass: LucideIcon
  export const ShoppingCart: LucideIcon
  export const ChevronDown: LucideIcon
  export const FileText: LucideIcon
  export const Plane: LucideIcon
  export const Upload: LucideIcon
  export const Clock: LucideIcon
  export const UserCheck: LucideIcon
  export const AlertCircle: LucideIcon
  export const Briefcase: LucideIcon
  export const RefreshCw: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowLeft: LucideIcon
  export const Filter: LucideIcon
  export const Mountain: LucideIcon
  export const Heart: LucideIcon
  export const Palmtree: LucideIcon
  export const Shield: LucideIcon
  export const Headphones: LucideIcon
  export const Wifi: LucideIcon
  export const Coffee: LucideIcon
  export const Car: LucideIcon
  export const Waves: LucideIcon
  export const Dumbbell: LucideIcon
  export const Utensils: LucideIcon
  export const CheckCircle: LucideIcon
  export const BadgeCheck: LucideIcon
  export const Globe: LucideIcon
  export const Phone: LucideIcon
  export const Mail: LucideIcon
  export const Camera: LucideIcon
  export const Play: LucideIcon
  export const Share2: LucideIcon
  export const Package: LucideIcon
  export const MapPinned: LucideIcon
  export const Tag: LucideIcon
  export const Tags: LucideIcon
  export const Sun: LucideIcon
  export const Moon: LucideIcon
  export const TrendingDown: LucideIcon
  export const ChevronRight: LucideIcon
  export const MoreVertical: LucideIcon
  export const EyeOff: LucideIcon
  export const UserPlus: LucideIcon
  export const ShieldCheck: LucideIcon
  export const Ban: LucideIcon
  export const Download: LucideIcon
  export const CheckCircle2: LucideIcon
  export const ArrowUpRight: LucideIcon
  export const Activity: LucideIcon
  export const UserCircle: LucideIcon
  export const Map: LucideIcon
  export const Lock: LucideIcon
  export const CalendarCheck: LucideIcon
  export const Zap: LucideIcon
  export const Navigation: LucideIcon
  export const MessageCircle: LucideIcon
  export const MessageSquare: LucideIcon
  export const Award: LucideIcon
  export const Leaf: LucideIcon
  export const Handshake: LucideIcon
  export const Sparkles: LucideIcon
  export const Landmark: LucideIcon
  export const Ticket: LucideIcon
  export const Lightbulb: LucideIcon
  export const Info: LucideIcon
  export const ChevronUp: LucideIcon
  export const Snowflake: LucideIcon
  export const Tv: LucideIcon
  export const Smartphone: LucideIcon
  export const Database: LucideIcon
  export const Languages: LucideIcon
  export const Bed: LucideIcon
  export const Wind: LucideIcon
  export const SortAsc: LucideIcon
  export const Undo: LucideIcon
  export const Crown: LucideIcon
  export const Send: LucideIcon
  export const CheckCheck: LucideIcon
  export const Minus: LucideIcon
  export const Maximize2: LucideIcon
  export const Facebook: LucideIcon
  export const Instagram: LucideIcon
  export const Twitter: LucideIcon
  export const Youtube: LucideIcon
}
